### 新手法「TAID」を用いた小規模日本語言語モデル「TinySwallow-1.5B」の公開
- 参考URL
1.   https://sakana.ai/taid-jp/
2.   https://github.com/SakanaAI/TinySwallow-ChatUI

In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

In [ ]:
# 1. load model
device = "cuda" if torch.cuda.is_available() else "cpu"
repo_id = "SakanaAI/TinySwallow-1.5B-Instruct"
model = AutoModelForCausalLM.from_pretrained(repo_id)
tokenizer = AutoTokenizer.from_pretrained(repo_id)
model.to(device)

config.json:   0%|          | 0.00/740 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.44k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 1536)
    (layers): ModuleList(
      (0-27): 28 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear(in_features=1536, out_features=1536, bias=True)
          (k_proj): Linear(in_features=1536, out_features=256, bias=True)
          (v_proj): Linear(in_features=1536, out_features=256, bias=True)
          (o_proj): Linear(in_features=1536, out_features=1536, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=1536, out_features=8960, bias=False)
          (up_proj): Linear(in_features=1536, out_features=8960, bias=False)
          (down_proj): Linear(in_features=8960, out_features=1536, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((1536,), eps=1e-06)
    (rotary_emb): Qw

In [ ]:
print(device)

cuda


In [ ]:
# 2. prepare inputs
text = "生成ALについて簡単に教えてください。"
messages = [{"role": "user", "content": text}]
input_ids = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt")


In [ ]:
print(text)

知識蒸留について簡単に教えてください。


In [ ]:
print(messages)

[{'role': 'user', 'content': '知識蒸留について簡単に教えてください。'}]


In [ ]:
print(input_ids)

tensor([[151644,   8948,    198, 126855,  15322,   5373,     50,    585,   3362,
          15235, 102868,  28330,  36993,  60237,  28195,  86347,  22859,    118,
          54951,  85693,  13218,   7183,  37541,   1773, 105911, 128822,   5373,
         112528, 127231,  16161, 103244, 100395,  25770,  38780,  56107, 124730,
          51314,  37541,   1773, 151645,    198, 151644,    872,    198, 110528,
         101494,  99337, 126288, 134382, 138592,  71215,   1773, 151645,    198,
         151644,  77091,    198]])


In [ ]:
# 3. generate
output_ids = model.generate(
    input_ids.to(device),
    max_new_tokens=1024,
)
print(output_ids)

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


tensor([[151644,   8948,    198, 126855,  15322,   5373,     50,    585,   3362,
          15235, 102868,  28330,  36993,  60237,  28195,  86347,  22859,    118,
          54951,  85693,  13218,   7183,  37541,   1773, 105911, 128822,   5373,
         112528, 127231,  16161, 103244, 100395,  25770,  38780,  56107, 124730,
          51314,  37541,   1773, 151645,    198, 151644,    872,    198, 110528,
         101494,  99337, 126288, 134382, 138592,  71215,   1773, 151645,    198,
         151644,  77091,    198,    565,  10236,  22129, 101000, 101494,  99337,
          15767,  99706,  30534,    271, 110528, 101494,  99337,   9909,  80334,
          27604,  66084,   7552, 126238,   5373,    334,  26288, 118331,  77144,
         102819, 134680, 129139,  99194, 106953,  47764, 101619, 134680,  53931,
         108521,  15767, 131552,  16161, 126721, 111387,  29412, 102573,  12857,
         126241, 124808,  53826, 107502,    334,  37541,   3407, 108247, 125009,
          27818,     16,    

In [ ]:
print(output_ids[:, input_ids.shape[1] :])

tensor([[   565,  10236,  22129, 101000, 101494,  99337,  15767,  99706,  30534,
            271, 110528, 101494,  99337,   9909,  80334,  27604,  66084,   7552,
         126238,   5373,    334,  26288, 118331,  77144, 102819, 134680,   9909,
         136175,  46358, 140530, 132687, 118331,  77144, 102819, 134680,   7552,
          53931, 108521,  15767, 131552,  16161,  47764, 101619, 138839, 138444,
         134680,  29412,  43959,  53826, 107502,    334,  37541,   3407,  14374,
            220, 132354, 100270, 131672,  26850,     12,   3070, 118460, 112695,
          95518,  40666,    100, 118331,  77144, 102819, 134680,  15322, 103475,
          26288,  25770, 118460,  36723, 124867,  60298,  29412, 100270,  19182,
          77334,   8997,     12,   3070, 141133,  95518,  20711,     95,  67308,
          32610, 132069,  28195, 137030, 128615,   5373, 134060,  24041,    233,
          93450,  70189,  83751, 100946,  19655, 134347,  81873,  19182, 112626,
          31877, 127535,  20

In [ ]:
output_ids = output_ids[:, input_ids.shape[1] :]
generated_text = tokenizer.batch_decode(output_ids, skip_special_tokens=True)[0]
print(generated_text)

:** 大きいサイズのモデル（例：BERT, GPT-3）
2. **生徒モデル:** 小さく軽量なモデル（例：TinyBERT）

という二つのモデルがあります。このとき、大きな教師モデルの出力を小さな生徒モデルにフィードバックすることで、生徒モデルの性能向上を目指します。

### 原理

教師モデルの知識や特徴を生徒モデルに「蒸留」して伝えることで、少ないデータでも高い性能を実現できます。これは、教師モデルの複雑な構造と能力を、よりシンプルで効率的な生徒モデルに圧縮・抽出することによって行われます。

### 用途

知識蒸留は様々な分野で活用されています。

* 自然言語処理: 文章生成、翻訳、質問応答など
* 機械翻訳: より低い計算コストでの高性能翻訳システムの構築
* 言語理解: テキスト要約、感情分析、意図認識など

### 注意点

知識蒸留では、教師モデルと生徒モデルの性能差異がある程度許容されます。そのため、生徒モデルの性能が教師モデルの性能よりも劣ることは避けられません。しかし、その差は比較的小さいことが望ましいと言えます。

以上のように、知識蒸留は限られたデータやリソースで高品質なモデルを開発するために有効な手法となっています。
もし他にも知りたいことがあれば、お気軽にお尋ねください！


In [ ]:
# 2. prepare inputs
text = "あなた自身を自己紹介してください。"
messages = [{"role": "user", "content": text}]
input_ids = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt")

# 3. generate
output_ids = model.generate(
    input_ids.to(device),
    max_new_tokens=1024,
)

output_ids = output_ids[:, input_ids.shape[1] :]
generated_text = tokenizer.batch_decode(output_ids, skip_special_tokens=True)[0]
print(generated_text)

私は、あなたの質問に答えるためにここにいます。

しかし、私の本当の名前や機能については詳しく説明できません。なぜなら、私はAIアシスタントであり、特定の名前を持つことはなく、また、個人情報保護の観点からも公開されていません。

ただし、私は以下のような能力を持っています：

* **情報提供:** 一般的な知識、事実、概念に関する情報を提供できます。
* **問題解決:** 特定のタスクや課題に対する提案や解決策を見つけるお手伝いをすることができます。
* **クリエイティブな思考:** 記事作成、物語作りなど、創造的な活動にも役立ちます。
* **学習支援:** 新しいスキルを身につけるためのリソースやヒントを提供します。

どのようなことについて知りたいですか？どんな助けが必要ですか？



In [ ]:
# 2. prepare inputs
text = "ブラウザで実行できる誕生年から年齢を計算するアプリを作って。"
messages = [{"role": "user", "content": text}]
input_ids = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt")

# 3. generate
output_ids = model.generate(
    input_ids.to(device),
    max_new_tokens=1024,
)

output_ids = output_ids[:, input_ids.shape[1] :]
generated_text = tokenizer.batch_decode(output_ids, skip_special_tokens=True)[0]
print(generated_text)

## 誕生日から年齢を計算するブラウザ用JavaScriptアプリ

このコードは、ユーザーの誕生日を入力すると、現在の日付と比較してその人の年齢を計算します。

```html
<!DOCTYPE html>
<html>
<head>
    <title>誕生日からの年齢</title>
</head>
<body>

<h1>誕生日からの年齢を計算する</h1>

<form id="ageForm">
  <label for="birthday">あなたの誕生日（yyyy/mm/dd）:</label><br>
  <input type="date" id="birthday" name="birthday"><br><br>
  <button type="submit">年齢を計算する</button>
</form>

<p id="message"></p>

<script>
const form = document.getElementById('ageForm');
const message = document.getElementById('message');

function calculateAge(birthday) {
  const today = new Date();
  const birthDate = new Date(birthday);

  if (birthDate > today) { // ユーザーが過去に生まれた場合
    message.textContent = "あなたはまだ生まれていません！";
    return;
  }

  let age = today.getFullYear() - birthDate.getFullYear();

  if (today.getMonth() < birthDate.getMonth()) {
    age--;
  } else if (today.getMonth() === birthDate.getMonth() && today.getDate() < birthDate.getDate()) {
    age--;
  }

  message.textContent = `あなたの年齢は ${age} 歳です`;
}